version: "3.8"

services:
  database:
    container_name: trillion-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "trillion-db"
      MYSQL_USER: "trillion-user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "topSecreTpassword"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "topSecreTpassword"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    networks:
      - trillion-code-blog-network
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
networks:
  trillion-code-blog-network:
