version: "3.8"

services:
  database:
    container_name: trillion-mysql
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "trillion-db"
      MYSQL_USER: "trillion-user"
      MYSQL_PASSWORD: "topSecreTpassword"
      MYSQL_ROOT_PASSWORD: "topSecreTpassword"
    ports:
      - "3306:3306"
    networks:
      - tcb-network
    volumes:
      - my-db:/var/lib/mysql
  rest-api:
    container_name: tcb-api
    image: tcb-api:1.0.0
    build:
      context: .
      dockerfile: ./api.Dockerfile
      args:
        NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - tcb-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
  client:
    container_name: tcb-nginx
    image: tcb-nginx:1.0.0
    build:
      context: .
      dockerfile: ./client.Dockerfile
    ports:
      - 8080:80
    networks:
      - tcb-network
    restart: unless-stopped
    depends_on:
      - rest-api
volumes:
  my-db:
networks:
  tcb-network:
